import type {Metadata} from "next";
import "@/styles/globals.css";
import Header from '@/components/Header'
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: "강건 사이트 테스트",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
