import type {Metadata} from "next";
import "@/styles/globals.css";
import Header from '@/components/Header'
import Footer from "@/components/Footer";
import {AuthProvider} from './context/AuthContext';
import React from "react";

export const metadata: Metadata = {
    title: "강건 사이트 테스트",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <AuthProvider>
            <Header/>
            {children}
            <Footer/>
        </AuthProvider>
        </body>
        </html>
    );
}
